export enum GameEvent {
	NONE,

	REGISTER_BUTTON,
	UNREGISTER_BUTTON,
	REDIRECT_PROCESSING,

	LEVEL_RESOURCES_PREPARED,
	LEVEL_NEXT,

	LETTER_POINTER_DOWN,
	LETTER_POINTER_UP,
	LETTER_POINTER_MOVE,
	LETTER_UNDER_POINTER,
	LETTER_ACTIVATE,
	LETTER_DEACTIVATE,
	LETTER_DEACTIVATE_ALL,

	WORD_CHECK,
	WORD_CORRECT,
	WORD_WRONG,
	WORD_DUBLICATE,

	CHECK_IF_FINISH,
	SHOW_ENDCARD,
}