export enum GameEvent {
	NONE,

	REGISTER_BUTTON,
	UNREGISTER_BUTTON,
	REDIRECT_PROCESSING,

	CAMERA_TRANSITION,

	LETTER_POINTER_DOWN,
	LETTER_POINTER_UP,
	LETTER_POINTER_MOVE,
	LETTER_UNDER_POINTER,
	MAIN_SCREEN_BUTTON_MOVE

}